name: Sync Templates and Create PR

on:
  push:
    paths:
      - "_template/**"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dev branch
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Set up Git configuration
        shell: bash
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Sync _template to tenant folders
        run: |
          echo "Syncing _template to tenant folders..."
          cp -r _template/* devops/ || true
          cp -r _template/* feature/ || true
          cp -r _template/* synergis/ || true

      - name: Create and push sync branch
        run: |
          BRANCH_NAME="sync/template-update-$(date +%s)"
          git checkout -b "$BRANCH_NAME"
          git add devops/ feature/ synergis/ || true
          git commit -m "Sync configs from _template" || echo "No changes to commit"
          git push origin "$BRANCH_NAME" || echo "No changes pushed"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if git diff --quiet origin/Dev...; then
            echo "No changes detected between Dev and $BRANCH_NAME"
            exit 0
          fi

          echo "Creating pull request for branch $BRANCH_NAME..."
          gh pr create \
            --base Dev \
            --head "$BRANCH_NAME" \
            --title "Sync configs from _template" \
            --body "This PR was automatically created by GitHub Actions to sync _template changes across all tenant folders."
