name: Sync Templates

on:
  push:
    paths:
      - "_template/**"
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  checks: read

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Set up Git configuration
        shell: bash
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Sync _template to tenants
        shell: bash
        run: |
          TENANTS=("devops" "feature" "synergis")
          for tenant in "${TENANTS[@]}"; do
            rsync -av --delete _template/ "$tenant/"
          done

      - name: Create sync branch if changes exist
        shell: bash
        run: |
          SYNC_BRANCH="sync/template-update-$(date +%s)"
          git checkout -b "$SYNC_BRANCH"
          git add devops/ feature/ synergis/
          if git diff --cached --quiet; then
            echo "No changes detected in tenant folders. Exiting."
            exit 0
          fi
          git commit -m "Synced configs from _template"
          echo "SYNC_BRANCH=$SYNC_BRANCH" >> $GITHUB_ENV

      - name: Push sync branch
        shell: bash
        run: |
          git push --set-upstream origin "$SYNC_BRANCH"

      - name: Create Pull Request
        if: env.SYNC_BRANCH != ''
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Synced configs from _template"
          branch: ${{ env.SYNC_BRANCH }}
          title: "Sync configs from _template"
          body: "This PR was automatically created by GitHub Actions to sync _template changes across all tenant folders."
          base: master
          draft: false
