name: Sync Templates and Create PR

on:
  push:
    paths:
      - "_template/**"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git configuration
        shell: bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Copy changes from _template to tenants
      - name: Sync _template to tenants
        run: |
          cp -r _template/* devops/ || true
          cp -r _template/* feature/ || true
          cp -r _template/* synergis/ || true

      # Commit and push changes to a new branch
      - name: Commit and push changes
        shell: bash
        run: |
          BRANCH_NAME="sync/template-update-$(date +%s)"
          git checkout -b "$BRANCH_NAME"
          git add devops/ feature/ synergis/
          git commit -m "Synced configs from _template" || echo "No changes to commit"
          git push origin "$BRANCH_NAME"

      # Create PR using GitHub API
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ steps.commit.outputs.branch_name }}
        run: |
          BASE_BRANCH=$(git rev-parse --abbrev-ref HEAD | sed 's/sync\/template-update-.*//')
          BRANCH_NAME=$(git branch --show-current)
          
          echo "Creating pull request for branch $BRANCH_NAME..."
          gh pr create \
            --base Dev \
            --head "$BRANCH_NAME" \
            --title "Sync configs from _template" \
            --body "This PR was automatically created by GitHub Actions to sync _template changes across all tenant folders."
