name: Sync Templates

on:
  push:
    branches:
      - master
    paths:
      - "_template/**"
  pull_request:
    branches:
      - master
    paths:
      - "_template/**"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Check for _template changes
        run: |
          if git diff HEAD^ HEAD --quiet -- _template/; then
            echo "No _template changes detected. Skipping sync."
            exit 0
          fi

      - name: Sync _template to tenants
        run: |
          TENANTS=("devops" "feature" "synergis")
          for tenant in "${TENANTS[@]}"; do
            mkdir -p "$tenant"
            rsync -av --delete _template/ "$tenant/"
          done
          git status

      - name: Commit and create PR
        run: |
          SYNC_BRANCH="sync/template-update-$(date +%s)"
          git checkout -b "$SYNC_BRANCH"
          git add devops/ feature/ synergis/
          if git diff --cached --quiet; then
            echo "No tenant changes detected. Exiting."
            exit 0
          fi
          git commit -m "Synced configs from _template"
          git push --set-upstream origin "$SYNC_BRANCH"
          echo "SYNC_BRANCH=$SYNC_BRANCH" >> $GITHUB_ENV

      - name: Create Pull Request
        if: env.SYNC_BRANCH != ''
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Synced configs from _template"
          branch: ${{ env.SYNC_BRANCH }}
          title: "Sync configs from _template"
          body: "Auto-synced _template changes to tenant folders."
          base: master
