name: Sync Templates

on:
  push:
    branches:
      - master
    paths:
      - "_template/**"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0   # ensures proper diff context

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Sync _template to tenants (excluding sensitive files)
        run: |
          TENANTS=("devops" "feature" "synergis")
          for tenant in "${TENANTS[@]}"; do
            mkdir -p "$tenant"
            rsync -av --checksum --delete \
              --exclude 'WebAPI/AdeptTenantLicense.json' \
              --exclude 'WebAPI/cognito-users.json' \
              _template/ "$tenant/"
          done

      - name: Check for changes
        id: check_changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No real content changes detected. Skipping PR."
            echo "skip_pr=true" >> $GITHUB_ENV
          else
            echo "Changes detected, will create PR."
            echo "skip_pr=false" >> $GITHUB_ENV
          fi

      - name: Create Pull Request
        if: env.skip_pr != 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync configs from _template"
          branch: sync/template-update
          title: "Sync configs from _template"
          body: |
            This PR was automatically created by GitHub Actions to sync `_template` changes across all tenant folders.

            Certain tenant-specific files like `AdeptTenantLicense.json` and `cognito-users.json` are intentionally excluded from `_template` sync to preserve per-tenant data.
          base: master
          delete-branch: true
