name: Sync Templates

on:
  push:
    branches:
      - master
    paths:
      - "_template/**"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0   # important: ensures we can diff correctly

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Sync _template to tenants
        run: |
          TENANTS=("devops" "feature" "synergis")
          for tenant in "${TENANTS[@]}"; do
            mkdir -p "$tenant"
            rsync -av --checksum --delete _template/ "$tenant/"
          done

      - name: Check for changes
        id: check_changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No real content changes detected. Skipping PR."
            echo "skip_pr=true" >> $GITHUB_ENV
          else
            echo "Changes detected, will create PR."
            echo "skip_pr=false" >> $GITHUB_ENV
            git diff --cached --name-only > diff.txt
            cat diff.txt
          fi

      - name: Create Pull Request
        if: env.skip_pr != 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync configs from _template"
          branch: sync/template-update
          title: "Sync configs from _template"
          body: |
            This PR was automatically created by GitHub Actions to sync `_template` changes across all tenant folders.

            **Changed tenant files:**
            ```
            $(cat diff.txt)
            ```
          base: master
          delete-branch: true
