name: Sync Templates

on:
  push:
    branches:
      - master
    paths:
      - "_template/**"
  pull_request:
    branches:
      - master
    paths:
      - "_template/**"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Sync _template to tenants
        run: |
          TENANTS=("devops" "feature" "synergis")
          for tenant in "${TENANTS[@]}"; do
            mkdir -p "$tenant"
            rsync -av --delete _template/ "$tenant/"
          done

      - name: Debug file differences
        run: |
          echo "Checking which files differ after sync:"
          git status
          git diff --name-only | tee diff.txt
          if [ -s diff.txt ]; then
            echo "Detected changed files:"
            cat diff.txt
          else
            echo "No actual changes detected. Nothing to commit."
          fi

      - name: Create and push sync branch if changes exist
        id: create_branch
        run: |
          if git diff --quiet; then
            echo "No tenant changes detected. Exiting."
            echo "skip_pr=true" >> $GITHUB_ENV
            exit 0
          fi

          SYNC_BRANCH="sync/template-update-$(date +%s)"
          git checkout -b "$SYNC_BRANCH"
          git add devops/ feature/ synergis/
          git commit -m "Synced configs from _template"
          git push --set-upstream origin "$SYNC_BRANCH"
          echo "SYNC_BRANCH=$SYNC_BRANCH" >> $GITHUB_ENV

      - name: Create Pull Request
        if: env.skip_pr != 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.SYNC_BRANCH }}
          title: "Sync configs from _template"
          body: |
            This PR was automatically created by GitHub Actions to sync `_template` changes across all tenant folders.

            **Changed tenant files:**
            ```
            $(cat diff.txt)
            ```
          base: master
          draft: false
