name: Sync Templates

on:
  push:
    paths:
      - "_template/**"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run sync script
        run: node scripts/sync-templates.js

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add devops/ feature/ synergis/
          git commit -m "Synced templates from _template" || echo "No changes to commit"
          git push
