name: Sync Templates

on:
  push:
    branches:
      - Dev
      - master
      - QA
      - Production
    paths:
      - "_template/**"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0   # ensures correct diff detection

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Sync _template to all tenant folders (excluding sensitive files)
        run: |
          for tenant_dir in */; do
            tenant_name=$(basename "$tenant_dir")

            # Skip the _template folder itself
            if [[ "$tenant_name" == "_template" ]]; then
              echo "Skipping _template folder"
              continue
            fi

            echo "Syncing template files to tenant: $tenant_name"
            rsync -av --checksum --delete \
              --exclude 'WebAPI/AdeptTenantLicense.json' \
              --exclude 'WebAPI/cognito-users.json' \
              _template/ "$tenant_name/"
          done

      - name: Check for changes
        id: check_changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "No real content changes detected. Skipping PR."
            echo "skip_pr=true" >> $GITHUB_ENV
          else
            echo "Changes detected, will create PR."
            echo "skip_pr=false" >> $GITHUB_ENV
          fi

      - name: Create Pull Request
        if: env.skip_pr != 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync configs from _template"
          branch: sync/template-update
          title: "Sync configs from _template"
          body: |
            This PR was automatically created by GitHub Actions to sync `_template` changes across all tenant folders.
            
            Tenant-specific files (`AdeptTenantLicense.json` and `cognito-users.json`) are intentionally excluded from syncing.
          base: ${{ github.ref_name }}
          delete-branch: true
